### ISSUE TITLE
댓글이 사라진 것 같습니다.

### ISSUE THREAD

**Issue by WDever** [jbee37142/1st-JBEE.io#125]
모든 포스트에서 댓글이 사라진 것 같습니다. 환경은 macOS 크롬 79 버전 입니다.

**Comment by jbee37142** [comment]
아 넵, 팔로업 중입니다 :) 제보 감사합니다.

https://github.com/utterance/utterances/issues/254

**Comment by WDever** [comment]
아 utterances 문제였군요. 해결 된 것 같습니다. 감사합니다.
