### ISSUE TITLE
자동생성된 브랜치 400개 정리하러 왔습니다.

### ISSUE THREAD

**Issue by cometkim** [jbee37142/1st-JBEE.io#52]
https://github.com/cometkim/cleankeeper

GitHub Action Beta 신청하신다음 요고 한번 써보세요 ㅎㅎ

**Comment by jbee37142** [comment]
@cometkim 
이게 벌써 한달... 정신이 없어서 아직 적용을 못해봤네요! 감사합니다! 꼭 사용해볼게요~
